/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;


/**
 *
 * @author Client
 */
public class ATMmainApp extends javax.swing.JFrame {
    
    AppLogIn main;
    private double Balance = 15000;
            
    public ATMmainApp(AppLogIn m) {
        initComponents();
        this.main = m;
    }
    public double getBalance(){
        return this.Balance;
    }
     
    void withdraw(int amount) {
        Balance -= amount;
    }
    void deposit(int amount){
        
        Balance += amount;
    }
    void fastcash(int amount){
        
        Balance -= amount;
    }
     void gtpassword (int pssword){
        main.getpassword(pssword);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DPbutton = new javax.swing.JButton();
        BIbutton = new javax.swing.JButton();
        CPbutton = new javax.swing.JButton();
        DevButton = new javax.swing.JButton();
        FCbutton = new javax.swing.JButton();
        WDbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Akira Expanded", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIDENTIAL BANK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 410, 80);

        DPbutton.setBackground(new java.awt.Color(0, 102, 51));
        DPbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DPbutton.setForeground(new java.awt.Color(255, 255, 255));
        DPbutton.setText("Deposit");
        DPbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(DPbutton);
        DPbutton.setBounds(270, 190, 170, 50);

        BIbutton.setBackground(new java.awt.Color(0, 102, 51));
        BIbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BIbutton.setForeground(new java.awt.Color(255, 255, 255));
        BIbutton.setText("Balanced Inquiry");
        BIbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(BIbutton);
        BIbutton.setBounds(60, 130, 170, 50);

        CPbutton.setBackground(new java.awt.Color(0, 102, 51));
        CPbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CPbutton.setForeground(new java.awt.Color(255, 255, 255));
        CPbutton.setText("Change PIN");
        CPbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(CPbutton);
        CPbutton.setBounds(60, 190, 170, 50);

        DevButton.setBackground(new java.awt.Color(0, 102, 51));
        DevButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DevButton.setForeground(new java.awt.Color(255, 255, 255));
        DevButton.setText("Developer");
        DevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DevButton);
        DevButton.setBounds(60, 250, 170, 50);

        FCbutton.setBackground(new java.awt.Color(0, 102, 51));
        FCbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FCbutton.setForeground(new java.awt.Color(255, 255, 255));
        FCbutton.setText("Fast Cash");
        FCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(FCbutton);
        FCbutton.setBounds(270, 250, 170, 50);

        WDbutton.setBackground(new java.awt.Color(0, 102, 51));
        WDbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WDbutton.setForeground(new java.awt.Color(255, 255, 255));
        WDbutton.setText("Withdraw");
        WDbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WDbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(WDbutton);
        WDbutton.setBounds(270, 130, 170, 50);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(70, 70, 350, 10);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 320, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPbuttonActionPerformed
        new Deposit(ATMmainApp.this).setVisible(true);
    }//GEN-LAST:event_DPbuttonActionPerformed

    private void BIbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIbuttonActionPerformed
        new BalanceInquiry(ATMmainApp.this).setVisible(true);
    }//GEN-LAST:event_BIbuttonActionPerformed

    private void CPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPbuttonActionPerformed
        new ChangePIN(ATMmainApp.this).setVisible(true);
    }//GEN-LAST:event_CPbuttonActionPerformed

    private void DevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevButtonActionPerformed
        new Developer().setVisible(true);
    }//GEN-LAST:event_DevButtonActionPerformed

    private void FCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCbuttonActionPerformed
        new FastCash(ATMmainApp.this).setVisible(true);
    }//GEN-LAST:event_FCbuttonActionPerformed

    private void WDbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WDbuttonActionPerformed
        new Withdraw(ATMmainApp.this).setVisible(true);
    }//GEN-LAST:event_WDbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMmainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMmainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMmainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMmainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIbutton;
    private javax.swing.JButton CPbutton;
    private javax.swing.JButton DPbutton;
    private javax.swing.JButton DevButton;
    private javax.swing.JButton FCbutton;
    private javax.swing.JButton WDbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
