/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author Client
 */
public class FastCash extends javax.swing.JFrame {

    ATMmainApp main;
    
    public FastCash(ATMmainApp m) {
        initComponents();
        this.main = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fc4 = new javax.swing.JButton();
        fc1 = new javax.swing.JButton();
        fc2 = new javax.swing.JButton();
        fc3 = new javax.swing.JButton();
        fc5 = new javax.swing.JButton();
        fc6 = new javax.swing.JButton();
        fc7 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        fc8 = new javax.swing.JButton();
        status = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Akira Expanded", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fast Cash");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 0, 300, 70);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 60, 340, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select the amount of your Fast Cash transaction;");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 360, 16);

        fc4.setBackground(new java.awt.Color(0, 102, 51));
        fc4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc4.setForeground(new java.awt.Color(255, 255, 255));
        fc4.setText("FC - 1000");
        fc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc4ActionPerformed(evt);
            }
        });
        jPanel1.add(fc4);
        fc4.setBounds(50, 280, 130, 30);

        fc1.setBackground(new java.awt.Color(0, 102, 51));
        fc1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc1.setForeground(new java.awt.Color(255, 255, 255));
        fc1.setText("FC - 100");
        fc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc1ActionPerformed(evt);
            }
        });
        jPanel1.add(fc1);
        fc1.setBounds(50, 160, 130, 30);

        fc2.setBackground(new java.awt.Color(0, 102, 51));
        fc2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc2.setForeground(new java.awt.Color(255, 255, 255));
        fc2.setText("FC - 200");
        fc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc2ActionPerformed(evt);
            }
        });
        jPanel1.add(fc2);
        fc2.setBounds(50, 200, 130, 30);

        fc3.setBackground(new java.awt.Color(0, 102, 51));
        fc3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc3.setForeground(new java.awt.Color(255, 255, 255));
        fc3.setText("FC - 500");
        fc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc3ActionPerformed(evt);
            }
        });
        jPanel1.add(fc3);
        fc3.setBounds(50, 240, 130, 30);

        fc5.setBackground(new java.awt.Color(0, 102, 51));
        fc5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc5.setForeground(new java.awt.Color(255, 255, 255));
        fc5.setText("FC - 1500");
        fc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc5ActionPerformed(evt);
            }
        });
        jPanel1.add(fc5);
        fc5.setBounds(230, 160, 130, 30);

        fc6.setBackground(new java.awt.Color(0, 102, 51));
        fc6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc6.setForeground(new java.awt.Color(255, 255, 255));
        fc6.setText("FC - 2000");
        fc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc6ActionPerformed(evt);
            }
        });
        jPanel1.add(fc6);
        fc6.setBounds(230, 200, 130, 30);

        fc7.setBackground(new java.awt.Color(0, 102, 51));
        fc7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc7.setForeground(new java.awt.Color(255, 255, 255));
        fc7.setText("FC - 2500");
        fc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc7ActionPerformed(evt);
            }
        });
        jPanel1.add(fc7);
        fc7.setBounds(230, 240, 130, 30);

        back.setBackground(new java.awt.Color(0, 102, 51));
        back.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(140, 320, 110, 30);

        fc8.setBackground(new java.awt.Color(0, 102, 51));
        fc8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        fc8.setForeground(new java.awt.Color(255, 255, 255));
        fc8.setText("FC - 3000");
        fc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc8ActionPerformed(evt);
            }
        });
        jPanel1.add(fc8);
        fc8.setBounds(230, 280, 130, 30);

        status.setEditable(false);
        status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status);
        status.setBounds(60, 110, 290, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc2ActionPerformed
        int fstcash = 200;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc2ActionPerformed

    private void fc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc6ActionPerformed
        int fstcash = 2000;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc6ActionPerformed

    private void fc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc7ActionPerformed
        int fstcash = 2500;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc7ActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void fc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc1ActionPerformed
        int fstcash = 100;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void fc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc3ActionPerformed
        int fstcash = 500;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc3ActionPerformed

    private void fc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc4ActionPerformed
        int fstcash = 1000;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc4ActionPerformed

    private void fc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc5ActionPerformed
       int fstcash = 1500;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc5ActionPerformed

    private void fc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc8ActionPerformed
        int fstcash = 3000;
        
        main.fastcash(fstcash);
        status.setText("Your " + fstcash + " Fast Cash transaction was Successful");
    }//GEN-LAST:event_fc8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton fc1;
    private javax.swing.JButton fc2;
    private javax.swing.JButton fc3;
    private javax.swing.JButton fc4;
    private javax.swing.JButton fc5;
    private javax.swing.JButton fc6;
    private javax.swing.JButton fc7;
    private javax.swing.JButton fc8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
